### ISSUE TITLE
Allow users to define element type

### ISSUE THREAD

**Issue by AlwynSmit** [hotosm/MapCampaigner#450]
# Problem

Currently user elements are confined by pre-loaded surveys.

# Proposed Solution

Allow users to define custom element types through the yaml interface.

requires #448

**Comment by AlwynSmit** [comment]
needs #448

**Comment by meomancer** [comment]
hi @AlwynSmit
could you explain this ticket?

**Comment by smit1678** [comment]
Reopening since I don't think this wasn't fully implemented or exposed via the UI. 

The goal of this ticket is to allow users to define whether they want to be tracking lines, polygons, or points or all. Right now we grab everything from Overpass that has a specific tag. These changes would allow a user to specify the element type -- for example, I want to get only all cafes that are points within OSM.

**Comment by pierrealixt** [comment]
Adding a geometry clause to the yaml.
Value can Point, Line or Polygon.

```
restaurant:
    feature: amenity
    tags:
        - amenity:
            - restaurant
            - fast-food
        - name
        - cuisine
    geometry: point
```
