### ISSUE TITLE
geojson filtering doesnt respect YAML geometry type

### ISSUE THREAD

**Issue by russbiggs** [hotosm/MapCampaigner#734]
with this YAML config:

```
building:
  feature: building
  tags:
    - 'addr:housenumber'
    - 'addr:street'
  element_type: Polygon
```

Points are showing on the map and being added into the calculation:

<img width="518" alt="Screen Shot 2019-10-15 at 8 17 13 AM" src="https://user-images.githubusercontent.com/8487728/66839833-4b23a880-ef24-11e9-9f0c-a0c37a9c6acc.png">

e.g. 
https://www.openstreetmap.org/node/6818655201
